apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: myapp
    image: nginx
  env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: myconfig
          key: course
