apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: resource
  labels:
    name: expense
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: "80"
